In [7]:
from bs4 import BeautifulSoup

# Collect Data

### Scrape Annenberg Landing Page

In [2]:
# mv /Users/spangher/Downloads/one_year_annenberg_media.html .

In [ ]:
landing_page_html = open('../data/one_year_annenberg_media.html').read()
soup = BeautifulSoup(landing_page_html)
all_list_items = soup.find_all('div', attrs={'class': 'list-item'})

In [15]:
import asyncio
from playwright.async_api import async_playwright

playwright = await async_playwright().start()
browser = await playwright.chromium.launch(headless=False)
page = await browser.new_page()
        
# To run this in Jupyter, use:
url = "https://www.uscannenbergmedia.com/allnews/"
await page.goto(url)

In [16]:
n_scrolls = 5  # Replace with however many scrolls you want
# page_content = await scroll_and_click_more(url, n_scrolls)

# To display the page content in a notebook
# print(page_content[:1000])  # Display the first 1000 characters

In [20]:
import time
from tqdm.auto import tqdm
for _ in tqdm(range(100)):
    # Scroll to the bottom of the page
    await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
    await asyncio.sleep(1)  # Give the page time to load

    try:
        await page.click("div.see-more")
    except:
        print("See More button not found or no more content to load.")
        break
    
    # Optional delay to avoid rate limiting or too-fast scrolling
    time.sleep(2)

  0%|          | 0/100 [00:00<?, ?it/s]

In [21]:
html = await page.content()

In [25]:
with open('../data/batch_collection_annenberg_media.html', 'w') as f:
    f.write(html)

### Scrape article pages

In [32]:
import requests

In [ ]:
soup = BeautifulSoup(html)
all_list_items = soup.find_all('div', attrs={'class': 'list-item'})
all_urls = list(map(lambda x: x.find('a')['href'], all_list_items))
homepage_domain = 'https://www.uscannenbergmedia.com'

In [41]:
# await page.goto(url)

In [43]:
all_article_pages = []
for url in tqdm(all_urls):
    r = requests.get(f'{homepage_domain}/{url}')
    all_article_pages.append(r.text)

  0%|          | 0/4240 [00:00<?, ?it/s]

In [47]:
ls ../data/

batch_collection_annenberg_media.html  one_year_annenberg_media.html

In [ ]:
import pandas as pd
import pickle
with open('../data/batch_collection_annenberg_html.pkl', 'wb') as f:
    pickle.dump( all_article_pages, f)

In [50]:
all_articles_parsed = list(map(lambda x: BeautifulSoup(x).get_text(' '), all_article_pages))

In [54]:
article_df = pd.DataFrame([all_urls, all_articles_parsed], index=['url', 'article_text']).T

In [56]:
article_df.to_csv('../data/batch_article_text.csv')

In [57]:
article_df

,url,article_text
0,/2024/10/08/dream-big-says-ezra-frech-a-two-ti...,"‘Dream big’ says Ezra Frech, a two-time Paraly..."
1,/2024/10/08/the-big-ten-breakdown-vol-3/,The Big Ten Breakdown Vol. 3: – Annenberg Medi...
2,/2024/10/08/review-linkin-park-marks-their-com...,Review: Linkin Park marks their comeback on a ...
3,/2024/10/07/call-her-president/,Call Her President? – Annenberg Media \n \n ...
4,/2024/10/07/usc-jewish-student-organizations-h...,USC Jewish student organizations host vigil fo...
...,...,...
4235,/2022/09/30/where-yoga-and-art-meet-how-one-in...,Where yoga and art meet: how one instructor br...
4236,/2022/09/30/grgurevic-mckenney-lead-usc-to-a-c...,"Grgurevic, McKenney lead USC to a comeback vic..."
4237,/2022/09/30/is-our-livelihood-not-important-re...,“Is our livelihood not important?”: Residents ...
4238,/2022/09/30/newsom-signs-law-allowing-californ...,Newsom signs law allowing California farmworke...
4239,/2022/09/30/what-call-me-crazy-told-me-about-m...,What “Call Me Crazy’” told me about myself – A...

In [44]:
# print(BeautifulSoup(r.text).get_text(' '))

# Article Df

In [218]:
import pickle 
with open('../data/batch_collection_annenberg_html.pkl', 'rb') as f:
    all_article_pages = pickle.load(f)

In [219]:
import pandas as pd 
article_df = pd.read_csv('../data/batch_article_text.csv')

In [3]:
import os 
os.environ['OPENAI_API_KEY'] = open('/Users/spangher/.openai-bloomberg-project-key.txt').read().strip()
from openai import OpenAI
client = OpenAI()

def prompt_openai(prompt, model='gpt-4o-mini'):
    completion = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}]
    )
    return completion.choices[0].message.content

In [52]:
CLEAN_ARTICLE_TEXT_PROMPT = """
You are a helpful editor assistant. I scraped this news article from the web and removed HTML tags, however, 
there is a lot of extraneous text from the HTML page that remains. Please only extract text related to the news article.
Do NOT miss any article text. 

Please preserve the paragraph breaks. 

Here is the news article:

<article>
{article_text}
</article>

Return the CLEANED text of the news article, the Headline and the Subheader (if it exists), nothing else. Return as a JSON:

Your response:
"""

CLEAN_ARTICLE_TEXT_FROM_HTML_PROMPT = """
You are a helpful editor assistant. Here is an HTML page I scraped from the web.
Please only extract text related to the news article. Do NOT miss any article text. Don't change or add any text that you return.

Please preserve all of the paragraph breaks. 

Here is the news article html:

<article html>
{article_html}
</article html>

Return the CLEANED text of the news article, the Headline and any Subheaders (if they exist), nothing else. Return as a JSON like so:

{{
'Headline': <headline_here>,
'Subheader': <subheader_here>,
'Article Body': <article_body>
}}

Your response:
"""

In [53]:
prompt = CLEAN_ARTICLE_TEXT_PROMPT.format(article_text=article_df['article_text'].iloc[0])
prompt = CLEAN_ARTICLE_TEXT_FROM_HTML_PROMPT.format(article_html=all_article_pages[0])

In [54]:
cleaned_article = prompt_openai(prompt)

In [ ]:
import json 
t = cleaned_article.replace('```json', '').replace('```', '')
json.loads(t)

In [37]:
paragraphs = cleaned_article.split('\n\n')

# Batch Jobs

## Parsing with BeautifulSoup + Cleaning

In [56]:
import tiktoken
from tqdm.auto import tqdm
from bs4 import BeautifulSoup
def remove_tags(html):
    soup = BeautifulSoup(html, "lxml")
    tags_to_remove = ['script', 'style', 'noscript', 'meta', 'link', 'iframe', 'footer', 'header', 'nav', 'form', 'hr', 'button', 'svg', 'img', 'picture', 'source']
    
    # Remove them
    for tag in soup(tags_to_remove):
        tag.decompose()
    return str(soup)

In [57]:
enc = tiktoken.get_encoding("o200k_base")

In [58]:
len(enc.encode(all_article_pages[0]))

71106

In [59]:
all_prompts = []
tokens = []
for html in tqdm(all_article_pages):
    stripped_html = remove_tags(html)
    prompt = CLEAN_ARTICLE_TEXT_FROM_HTML_PROMPT.format(article_html=stripped_html) 
    all_prompts.append(prompt)
    tokens.append(len(enc.encode(prompt)))

  0%|          | 0/4240 [00:00<?, ?it/s]

In [61]:
# all_tokens = sum(list(map(len, tokens)))
all_tokens = sum(tokens)
all_tokens / 1_000_000 * 0.150

3.2213808

In [78]:
output = prompt_openai(prompt)

In [ ]:
len(enc.encode(output))

In [94]:
mkdir openai_batched_data

In [62]:
all_batched_prompts = []
for prompt_id, prompt in tqdm(enumerate(all_prompts)):
    all_batched_prompts.append({
        "custom_id": f"request-{prompt_id}",
        "method": "POST",
        "url": "/v1/chat/completions",
        "body": {
            "model": "gpt-4o-mini", 
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": len(enc.encode(prompt))
        }
    })

0it [00:00, ?it/s]

In [63]:
import jsonlines
with jsonlines.open('openai_batched_data/batch_input.jsonl', 'w') as f:
    f.write_all(all_batched_prompts)

batch_input_file = client.files.create(
    file=open("openai_batched_data/batch_input.jsonl", "rb"),
    purpose="batch"
)

print(batch_input_file)

FileObject(id='file-BApbVRkYQz1EZPX2VWz2Ay', bytes=78799059, created_at=1746664105, filename='batch_input.jsonl', object='file', purpose='batch', status='processed', expires_at=None, status_details=None)

In [65]:
batch_input_file_id = batch_input_file.id
client.batches.create(
    input_file_id=batch_input_file_id,
    endpoint="/v1/chat/completions",
    completion_window="24h",
    metadata={
        "description": "nightly eval job"
    }
)

Batch(id='batch_681bfabe03d48190a8b6ba2379e56763', completion_window='24h', created_at=1746664126, endpoint='/v1/chat/completions', input_file_id='file-BApbVRkYQz1EZPX2VWz2Ay', object='batch', status='validating', cancelled_at=None, cancelling_at=None, completed_at=None, error_file_id=None, errors=None, expired_at=None, expires_at=1746750526, failed_at=None, finalizing_at=None, in_progress_at=None, metadata={'description': 'nightly eval job'}, output_file_id=None, request_counts=BatchRequestCounts(completed=0, failed=0, total=0))

In [ ]:
# batch_681bfab14fe4819080c85842186af49c
# batch_681bfabe03d48190a8b6ba2379e56763

In [375]:
pyperclip.copy(p.MULTI_SENTENCE_LABELING_PROMPT)

In [99]:
b = client.batches.retrieve("batch_681bfabe03d48190a8b6ba2379e56763")
file_response = client.files.content("file-NLfqfrdrY8Ar5U69kjTBPp")

In [100]:
import json

In [101]:
file_response.text[:100]

'{"id": "batch_req_681c020e998081909a9b424fa2ee2ac4", "custom_id": "request-0", "response": {"status_'

In [102]:
with open('openai_batched_data/cleaned_articles_with_headlines-1.jsonl', 'w') as f:
    f.write(file_response.text)

In [129]:
parsed_files = glob.glob('openai_batched_data/cleaned_articles_with_headlines-1.jsonl')

parsed_df = pd.concat(list(map(lambda x: pd.read_json(x, lines=True), parsed_files))).reset_index(drop=True)
parsed_df['label'] = parsed_df['response'].str.get('body').str.get('choices').str.get(0).str.get('message').str.get('content')
parsed_df['label'] = parsed_df['label'].str.replace('```json', '').str.replace('```', '').apply(robust_json_parse)
fully_parsed_df = (parsed_df
 .loc[lambda df: df['label'].notnull()]
 .pipe(lambda df: pd.concat([df[['custom_id']].reset_index(drop=True), pd.DataFrame(df['label'].tolist())] , axis=1))
)

<unknown>:4: SyntaxWarning: invalid escape sequence '\ '

### LA Times

In [ ]:
import glob

# latimes
latimes_articles_df = pd.read_json('../../newsworthiness/data/articles/latimes-8-years.jsonl', lines=True)
latimes_homepages = []
for csv_file in glob.glob('../../newsworthiness/data/homepages/8-years-latimes-homepage-csvs/*'):
    latimes_homepages.append(pd.read_csv(csv_file))
latimes_homepages_df = pd.concat(latimes_homepages)

In [79]:
full_latimes_articles_w_headline_df = (
    latimes_articles_df
         .drop_duplicates('article_url')
         .merge(
             latimes_homepages_df.drop_duplicates('href').drop(columns='Unnamed: 0'), 
             left_on='article_url', right_on='href'
         )
         .reset_index().rename(columns={'index': 'doc_id'})
)

latimes_articles_w_headline_df = (
    full_latimes_articles_w_headline_df
        .loc[lambda df: df['link_text'].notnull()]
        .loc[lambda df: df['homepage_key'] > 20210101000000]
        .loc[lambda df: df['article_text'].str.split().str.len() > 100]
        .loc[lambda df: ~df['article_url'].str.contains('/world-nation/')]
        .sample(8_000)
)

In [110]:
mkdir ../data/latimes

In [103]:
# latimes_articles_w_headline_df

In [171]:
(latimes_articles_w_headline_df
 [['id', 'link_text', 'all_text', 'article_publish_date', 'article_wayback_timestamp', 'article_url', 'article_text']]
 .to_csv('../data/latimes/article-text-and-headlines.csv')
)

In [187]:
import prompts as p
from importlib import reload
reload(p)

In [227]:
tqdm.pandas()
num_sents_per_prompt = 8
latimes_prompt_df = []
for _, row in tqdm(latimes_articles_w_headline_df.iterrows(), total=len(latimes_articles_w_headline_df)):
    article_text = row['article_text']
    sents = list(map(str, nlp(article_text).sents))
    for i in range(0, len(sents), num_sents_per_prompt):
        sents_chunk = sents[i: i + num_sents_per_prompt]
        sents_chunk = list(map(lambda x: f"({i + x[0]}) {x[1].replace('\n', ' ').strip()}", enumerate(sents_chunk)))
        sents_chunk = '\n'.join(sents_chunk)
        prompt = p.MULTI_SENTENCE_LABELING_PROMPT.format(k=num_sents_per_prompt, story=article_text, sentences=sents_chunk)
        latimes_prompt_df.append({
            'doc_id': row['doc_id'],
            'sents': sents,
            'prompt': prompt,
        })
latimes_prompt_df = pd.DataFrame(latimes_prompt_df)

  0%|          | 0/8000 [00:00<?, ?it/s]

In [ ]:
latimes_prompt_df = pd.DataFrame(latimes_prompt_df)
latimes_prompt_df = latimes_prompt_df.reset_index().assign(prompt_id=lambda df: 'doc_id-' + df['doc_id'].astype(str) + '__prompt_id-' + df['index'].astype(str))

In [229]:
tok_lens = latimes_prompt_df.head(5_000)['prompt'].progress_apply(lambda x: len(enc.encode(x)))

  0%|          | 0/5000 [00:00<?, ?it/s]

In [230]:
tok_lens.sum() * (len(latimes_prompt_df) / 5_000) / 1_000_000 * 0.150

24.519370068449998

In [243]:
prompt = latimes_prompt_df['prompt'].iloc[10]

In [244]:
o = prompt_openai(prompt)

In [251]:
all_batched_prompts = []
for _, (prompt_id, prompt) in tqdm(latimes_prompt_df[['prompt_id', 'prompt']].iterrows()):
    all_batched_prompts.append({
        "custom_id": prompt_id,
        "method": "POST",
        "url": "/v1/chat/completions",
        "body": {
            "model": "gpt-4o-mini", 
            "messages": [{
                "role": "user", "content": prompt
            }],
        }
    })

0it [00:00, ?it/s]

In [253]:
import jsonlines

batch_size = 10_000
batched_input_files = []
for i in tqdm(range(int(len(all_batched_prompts) / batch_size) + 1)):
    filename = f'openai_batched_data/latimes_labeling_batched_input_{i}.jsonl'
    with jsonlines.open(filename, 'w') as f:
        f.write_all(all_batched_prompts[i * batch_size: (i+1) * batch_size])

    batch_input_file = client.files.create(file=open(filename, "rb"), purpose="batch")    
    batched_input_files.append(batch_input_file)

  0%|          | 0/6 [00:00<?, ?it/s]

In [255]:
batches = []
for b in batched_input_files:
    batch_input_file_id = b.id
    c = client.batches.create(
        input_file_id=batch_input_file_id,
        endpoint="/v1/chat/completions",
        completion_window="24h",
        metadata={
            "description": "nightly eval job"
        }
    )
    batches.append(c)

In [1]:
latimes_batch_ids = [
    'batch_681c0eea38588190a187a83d856072ee',
    'batch_681c0eeac6108190b8df3bde1d5699d4',
    'batch_681c0eeb02d4819084f34b9ac88749b5',
    'batch_681c0eeb37c88190ab6bee72f0d00e4c',
    'batch_681c0eeb69988190a2c34478e010c1a8',
    'batch_681c0eebf9ec8190bdf324cdd5f2f695',
]

In [14]:
import json

In [37]:
all_results = []
for batch_id in latimes_batch_ids:
    b = client.batches.retrieve(batch_id)
    if b.output_file_id is not None:
        file_response = client.files.content(b.output_file_id)
        
        ####
        for line in file_response.iter_lines():
            if line:
                result = json.loads(line)
                result_str = result['response']['body']['choices'][0]['message']['content']
                result_str = result_str.replace('```json', '').replace('```', '')
                parsed_result = robust_json_parse(result_str)
                all_results.append({
                    'id': result['custom_id'],
                    'output': parsed_result
                })

In [40]:
all_results_df = pd.DataFrame(all_results).explode('output')

In [ ]:
tqdm.pandas()
latimes_sent_df = (
    full_latimes_articles_w_headline_df
         .assign(sents=lambda df: df['article_text'].progress_apply(lambda x: list(map(str, nlp(x).sents))))
         .drop(columns=['article_wayback_timestamp', 'all_text'])
)

latimes_sent_df_exp = (
    latimes_sent_df
        .assign(sents=lambda df: df['sents'].apply(lambda x: list(enumerate(x))))
        .explode('sents')
        .assign(sentence_index=lambda df: df['sents'].str.get(0))
        .assign(sent=lambda df: df['sents'].str.get(1))
        .drop(columns='sents')
        .rename(columns={'id': 'doc_id'})
)

In [83]:
all_results_df_exp = (
    all_results_df
         .loc[lambda df: df['output'].notnull()].pipe(lambda df: pd.concat([
            df[['id']].reset_index(drop=True),
            pd.DataFrame(df['output'].tolist())
        ], axis=1))
     .assign(doc_id=lambda df: df['id'].str.split('__').str.get(0).str.replace('doc_id-', '').astype(int))
)

In [252]:
merged_latimes_df = (
    latimes_sent_df_exp
         .merge(all_results_df_exp)
         .sort_values(['doc_id', 'sentence_index'])
         .groupby(['doc_id', 'link_text', 'article_publish_date', 'article_url', 'article_text'])
         [['sent', 'label', 'justification']].aggregate(list)
         .reset_index()
         .rename(columns={'link_text': 'article_headline'})
)

In [253]:
merged_latimes_df.to_json('../data/for_retriv/latimes-full-articles.jsonl', orient='records', lines=True)

## Annenberg Article Labeling

In [172]:
import ast
def robust_json_parse(x):
    try:
        return json.loads(x)
    except:
        try:
            return ast.literal_eval(x)
        except:
            return None 

import spacy
import sys
sys.path.insert(0, '../app/app/')
from tqdm.auto import tqdm
import jsonlines
import pandas as pd

nlp = spacy.load('en_core_web_lg', disable=["tagger", "parser", "ner", "lemmatizer", "attribute_ruler", "tok2vec", "morphologizer"])
for pipe in list(nlp.pipe_names):
    nlp.remove_pipe(pipe)
nlp.add_pipe("sentencizer")

all_cleaned_articles = list(jsonlines.open('openai_batched_data/cleaned_articles_with_headlines-1.jsonl'))

In [173]:
all_cleaned_article_df = pd.DataFrame(all_cleaned_articles)
all_cleaned_article_df['parsed_packet'] = (
    all_cleaned_article_df
         ['response'].str.get('body').str.get('choices').str.get(0).str.get('message').str.get('content')
         .str.replace('```json', '').str.replace('```', '')
         .str.replace('”\n}', '"\n}')
         .str.strip()
         .apply(robust_json_parse)
)

all_cleaned_article_df = all_cleaned_article_df.loc[lambda df: df['parsed_packet'].notnull()]

all_cleaned_article_df = pd.concat([
    all_cleaned_article_df[['custom_id']].reset_index(drop=True),
    all_cleaned_article_df['parsed_packet'].pipe(lambda df: pd.DataFrame(df.tolist()))
], axis=1)

<unknown>:4: SyntaxWarning: invalid escape sequence '\ '

In [174]:
all_cleaned_article_df.head(2)

,custom_id,Headline,Subheader,Article Body
0,request-0,"‘Dream big’ says Ezra Frech, a two-time Paraly...","Frech shares his journey as an athlete, emphas...",Record-breaking triumph at the 2024 Paralympic...
1,request-1,The Big Ten Breakdown Vol. 3:,Where each new-look conference stands halfway ...,We are somehow already nearly halfway through ...

In [ ]:
tqdm.pandas()
num_sents_per_prompt = 8
all_prompt_dfs = []
for _, r in tqdm(all_cleaned_article_df.iterrows(), total=len(all_cleaned_article_df)):
    orig_id = r['custom_id']
    article_text = r['Article Body']
    sents = list(map(lambda x: str(x).strip(), nlp(article_text).sents))
    for i in range(0, len(sents), num_sents_per_prompt):
        sents_chunk = sents[i: i + num_sents_per_prompt]
        sents_chunk = list(map(lambda x: f"({i + x[0]}) {x[1].replace('\n', ' ').strip()}", enumerate(sents_chunk)))
        sents_chunk = '\n'.join(sents_chunk)
        prompt = p.MULTI_SENTENCE_LABELING_PROMPT.format(k=num_sents_per_prompt, story=article_text, sentences=sents_chunk)
        all_prompt_dfs.append({
            'doc_id': orig_id,
            'sents': sents,
            'prompt': prompt,
        })
        
all_prompt_dfs = pd.DataFrame(all_prompt_dfs)
all_prompt_dfs = all_prompt_dfs.assign(prompt_id=lambda df: df['doc_id'] + '__' + df.reset_index()['index'].astype(str))

In [ ]:
## old, for keeping track of paragraphs
if False:
    all_paragraph_dfs = []
    for _, r in tqdm(all_cleaned_article_df.iterrows()):
        orig_id = r['custom_id']
        output = r['Article Body']
        paragraphs = pd.Series(output.split('\n\n')).to_frame('text')
        paragraph_df = (
            paragraphs
                 .reset_index().rename(columns={'index': 'paragraph_id'})
                 # .assign(char_len=lambda df: df['text'].str.len())
                 # .assign(end_char=lambda df: df['char_len'].cumsum())
                 # .assign(start_char=lambda df: [0] + df['end_char'].tolist()[:-1])
                 .assign(sents=lambda df: df['text'].apply(lambda x: list(map(str, nlp(x).sents))))
                 .drop(columns='text')
                 .explode('sents')
                 .reset_index(drop=True)
                 .reset_index().rename(columns={'index': 'sent_id'})
                 .assign(prompt=lambda df: df['sents'].apply(lambda x: LABELING_PROMPT.format(story=output, sentence=x)))
        )
        paragraph_df['doc_id'] = orig_id
        all_paragraph_dfs.append(paragraph_df)
    full_labeling_df = pd.concat(all_paragraph_dfs).assign(prompt_id=lambda df: df['doc_id'] + '__' + df['paragraph_id'].astype(str) + '__' + df['sent_id'].astype(str))

In [363]:
tqdm.pandas()
prompt_lens = all_prompt_dfs['prompt'].progress_apply(lambda x: len(enc.encode(x)))

  0%|          | 0/20125 [00:00<?, ?it/s]

In [364]:
(prompt_lens.sum() / 1_000_000 * 0.150) / 2

3.78895365

In [365]:
all_batched_prompts = []
for _, (prompt_id, prompt) in tqdm(all_prompt_dfs[['prompt_id', 'prompt']].iterrows()):
    all_batched_prompts.append({
        "custom_id": f"request-{prompt_id}",
        "method": "POST",
        "url": "/v1/chat/completions",
        "body": {
            "model": "gpt-4o-mini", 
            "messages": [{
                "role": "user", "content": prompt
            }],
        }
    })

0it [00:00, ?it/s]

In [366]:
len(all_batched_prompts)

20125

In [367]:
import jsonlines

batch_size = 5_000
batched_input_files = []
for i in tqdm(range(int(len(all_batched_prompts) / batch_size) + 1)):
    filename = f'openai_batched_data/new_labeling_batched_input_{i}.jsonl'
    with jsonlines.open(filename, 'w') as f:
        f.write_all(all_batched_prompts[i * batch_size: (i+1) * batch_size])

    batch_input_file = client.files.create(file=open(filename, "rb"), purpose="batch")    
    batched_input_files.append(batch_input_file)

  0%|          | 0/5 [00:00<?, ?it/s]

In [368]:
batches = []
for b in batched_input_files:
    batch_input_file_id = b.id
    c = client.batches.create(
        input_file_id=batch_input_file_id,
        endpoint="/v1/chat/completions",
        completion_window="24h",
        metadata={
            "description": "nightly eval job"
        }
    )
    batches.append(c)

In [369]:
list(map(lambda x: x.id, batches))

['batch_681c150be908819089ff4994b768050e',
 'batch_681c150c4b688190871200c895f0c9ad',
 'batch_681c150c7e5481908461b21a6e65da6e',
 'batch_681c150cea4c81908cd2323605c5fc8d',
 'batch_681c150d2a8881908e17ba67d3c6e225']

In [ ]:
retrieved_batches = list(map(lambda x: client.batches.retrieve(x.id), batches))
file_response = client.files.content("file-EHuWju3FM1ckQeDTXx1fVu")
for i, b in enumerate(retrieved_batches):
    file_response = client.files.content(b.output_file_id)
    with open(f'openai_batched_data/cleaned_articles__batch-{i}.jsonl', 'w') as f:
        f.write(file_response.text)

In [134]:
new_batch_ids = [
 'batch_681c150be908819089ff4994b768050e',
 'batch_681c150c4b688190871200c895f0c9ad',
 'batch_681c150c7e5481908461b21a6e65da6e',
 'batch_681c150cea4c81908cd2323605c5fc8d',
 'batch_681c150d2a8881908e17ba67d3c6e225'
]

for i, batch_id in enumerate(new_batch_ids):
    retrieved_batch = client.batches.retrieve(batch_id)
    file_response = client.files.content(retrieved_batch.output_file_id)
    with open(f'openai_batched_data/new_cleaned_articles__batch-{i}.jsonl', 'w') as f:
        f.write(file_response.text)

# Analyse chunks

In [137]:
import glob, jsonlines
import pandas as pd 
labeled_files = glob.glob('openai_batched_data/new_cleaned_articles__batch-*')
# labeled_files = glob.glob('openai_batched_data/cleaned_articles_with_headlines-1.jsonl')

labeled_df = pd.concat(list(map(lambda x: pd.read_json(x, lines=True), labeled_files))).reset_index(drop=True)
labeled_df['label'] = labeled_df['response'].str.get('body').str.get('choices').str.get(0).str.get('message').str.get('content')
labeled_df['label'] = labeled_df['label'].str.replace('```json', '').str.replace('```', '').apply(robust_json_parse)
# labeled_df['label'] = labeled_df['label'].str.replace('>', '').str.replace('<', '').str.title().str.split('\n').str.get(0)

In [162]:
labeled_df_exp = (
    labeled_df
     .explode('label')
     .loc[lambda df: df['label'].notnull()]
     .pipe(lambda df: pd.concat([
         df[['custom_id']].reset_index(drop=True), 
         pd.DataFrame(df['label'].tolist())
    ], axis=1))
     .assign(doc_id=lambda df: df['custom_id'].str.split('__').str.get(0).str.replace('request-request-', '').astype(int))
    .rename(columns={'sentence_index': 'sent_id'}).drop(columns='custom_id')
)

In [164]:
labeled_df_exp.head(2)

   sent_id label                                      justification  doc_id
0        0  Lede  This sentence introduces the column, its autho...    3153
1        1  Lede  This sentence creates an engaging hook by indi...    3153

In [165]:
t = list(jsonlines.open('openai_batched_data/labeling_batched_input_0.jsonl'))[0]['body']
orig_definitions = t['messages'][0]['content'].split('<definitions>')[1].split('</definitions>')[0].strip().split('\n')
orig_definitions = list(map(lambda x: x.split('**')[1], orig_definitions))
orig_definitions = pd.Series(orig_definitions).str.title()

In [166]:
labeled_df_exp['label'] = labeled_df_exp['label'].apply(lambda x: x if x in set(orig_definitions.tolist()) else 'Other')

In [188]:
tqdm.pandas()
all_cleaned_article_sent_df = (
    all_cleaned_article_df
         .assign(sents=lambda df: df['Article Body'].progress_apply(lambda x: list(map(str, nlp(x).sents))))
)

all_cleaned_article_sent_df_exp = (
    all_cleaned_article_sent_df
        .assign(sents=lambda df: df['sents'].apply(lambda x: list(enumerate(x))))
        .explode('sents')
        .assign(sentence_index=lambda df: df['sents'].str.get(0))
        .assign(sent=lambda df: df['sents'].str.get(1))
        .drop(columns='sents')
        .loc[lambda df: df['sentence_index'].notnull()]
        .assign(doc_id=lambda df: df['custom_id'].str.replace('request-', '').astype(int))
        .rename(columns={'id': 'doc_id', 'sentence_index': 'sent_id'})
        .assign(sent_id=lambda df: df['sent_id'].astype(int))
)

  0%|          | 0/4204 [00:00<?, ?it/s]

In [190]:
# labeled_df_exp.sort_values(['doc_id', 'sent_id']).groupby('doc_id').groupby('doc_id')[['label', 'justification']]

In [175]:
(
    all_cleaned_article_df
         .assign(doc_id=lambda df: df['custom_id'].str.replace('request-', '').astype(int))
         .head(3)
)

,custom_id,Headline,Subheader,Article Body,doc_id
0,request-0,"‘Dream big’ says Ezra Frech, a two-time Paraly...","Frech shares his journey as an athlete, emphas...",Record-breaking triumph at the 2024 Paralympic...,0
1,request-1,The Big Ten Breakdown Vol. 3:,Where each new-look conference stands halfway ...,We are somehow already nearly halfway through ...,1
2,request-2,Review: Linkin Park marks their comeback on a ...,A mainstay for angst-filled teenagers in the 2...,What band comes to mind when you think of “nu ...,2

In [194]:
# sent_df_with_labels = (
#     full_labeling_df
#             [['sent_id', 'paragraph_id', 'doc_id', 'sents', 'prompt_id']].merge(
#             labeled_df.assign(prompt_id=lambda df: df['custom_id'].str.replace('request-request-', 'request-'))[['prompt_id', 'label']]
#         )
#      .drop(columns='prompt_id')
# )

# documents = sent_df_with_labels.groupby('doc_id').apply(lambda df: ' '.join(df.sort_values('sent_id')['sents'].dropna()))

# documents_to_dump = (
#     pd.concat([
#         documents.to_frame('text'),
#         sent_df_with_labels.groupby('doc_id')[['sents', 'label']].aggregate(list)
#     ], axis=1)
#     .rename(columns={0: 'text', 'sents':'sentences', 'label': 'labels'})
# )

In [195]:
merged_latimes_df.head(2)

,doc_id,link_text,article_publish_date,article_url,article_text,sent,label,justification
0,65448,‘Separate and unequal’: South L.A.'s MLK hosp...,2021-01-01 13:00:44.528000,https://www.latimes.com/california/story/2021-...,Under the hum of mechanical equipment and the ...,[Under the hum of mechanical equipment and the...,"[Lede, Color, Transition, Nut Graf, Nut Graf, ...",[This sentence captures the attention of the r...
1,65451,Inside the shutdown of pandemic party app Vyb...,2021-01-01 02:07:54.567000,https://www.latimes.com/entertainment-arts/mus...,Just a few hours before New York City began wi...,[Just a few hours before New York City began w...,"[Lede, Quote, Quote, Nut Graf, Quote, Quote, B...",[This sentence introduces the main character a...

In [244]:
merged_annenberg_df = (
    labeled_df_exp
         .merge(all_cleaned_article_sent_df_exp)
         .sort_values(['doc_id', 'sent_id', ])
         .groupby(['doc_id', 'Headline', 'Article Body'])
         [['Subheader', 'sent', 'label', 'justification']]
         .aggregate(list)
         .assign(Subheader=lambda df: df['Subheader'].str.get(0))
         .reset_index()
         .merge(
                (article_df
                     .rename(columns={'Unnamed: 0': 'doc_id'})
                     .assign(url=lambda df: 'https://www.uscannenbergmedia.com' + df['url'])
                    )[['doc_id', 'url']]
            )
         .rename(columns={
             'Headline': 'article_headline', 
             'Subheader': 'article_subheader', 
             'url': 'article_url',
             'Article Body': 'article_text'
         })
)

In [254]:
merged_latimes_df.head(2)

,doc_id,article_headline,article_publish_date,article_url,article_text,sent,label,justification
0,65448,‘Separate and unequal’: South L.A.'s MLK hosp...,2021-01-01 13:00:44.528000,https://www.latimes.com/california/story/2021-...,Under the hum of mechanical equipment and the ...,[Under the hum of mechanical equipment and the...,"[Lede, Color, Transition, Nut Graf, Nut Graf, ...",[This sentence captures the attention of the r...
1,65451,Inside the shutdown of pandemic party app Vyb...,2021-01-01 02:07:54.567000,https://www.latimes.com/entertainment-arts/mus...,Just a few hours before New York City began wi...,[Just a few hours before New York City began w...,"[Lede, Quote, Quote, Nut Graf, Quote, Quote, B...",[This sentence introduces the main character a...

In [256]:
merged_annenberg_df.head(2)

,doc_id,article_headline,article_text,article_subheader,sent,label,justification,article_url
0,0,"‘Dream big’ says Ezra Frech, a two-time Paraly...",Record-breaking triumph at the 2024 Paralympic...,"Frech shares his journey as an athlete, emphas...",[Record-breaking triumph at the 2024 Paralympi...,"[Lede, Quote, Quote, Quote, Nut Graf, Backgrou...",[This sentence opens the article with the main...,https://www.uscannenbergmedia.com/2024/10/08/d...
1,1,The Big Ten Breakdown Vol. 3:,We are somehow already nearly halfway through ...,Where each new-look conference stands halfway ...,[We are somehow already nearly halfway through...,"[Lede, Nut Graf, Background Information, Analy...",[This sentence serves as the opening to the st...,https://www.uscannenbergmedia.com/2024/10/08/t...

In [257]:
# docs_for_retriv = documents_to_dump.reset_index().rename(columns={'doc_id': 'id'})
# docs_for_retriv.to_json('../data/for_retriv/annenberg-full-articles.jsonl',orient='records', lines=True)
merged_annenberg_df.to_json('../data/for_retriv/annenberg-full-articles-w-headline.jsonl',orient='records', lines=True)

In [ ]:
CHUNKING_PROMPT = """
You are a helpful editor assistant. I scraped this news article from the web and removed HTML tags, however, 
there is a lot of extraneous text from the HTML page that remains. Please only extract text related to the news article.
Do NOT miss any article text. Here is the news article:

<article>
{article_text}
</article>

Return only the CLEANED text of the news article, nothing else.

Your response:
"""

In [268]:
import pyperclip

In [276]:
t = {
    "prompt": "I will show you a student-written draft and a professionally-edited article, each with structural annotations for each sentence. The structural annotations are the following:\n\n<definitions>\nLede: The opening sentence or sentences of a story that grabs the reader's attention and highlights the most important and newsworthy aspects, usually including the \"who, what, when, where, why and how\" elements in succinct language.\nNut Graf: Context for the story: Why the audience cares, why the topic matters and other crucial details relevant to the story.\nBackground Information: Contextual information related to the main topic of the story.\nAttribution: Person, organization or document that provides information.\nEvidence: Information that supports the main point.\nQuote: Exact words from someone you interviewed or documents you reviewed.\nCounterargument: This is a crucial part of the story that displays evidence that the reporter has considered and consulted experts on possible rebuttals to the story's main topic or contention.\nTransition: A sentence that indicates a new idea or topic is being introduced.\nSupporting Detail: More information about an idea or topic that is intended to help the reader take action, deepen their understanding of the information or draw a conclusion.\nSource Opinion: An opinionated statement from an individual who spoke directly or indirectly to a reporter.\nAuthor Point of View: An opinion expressed by the author that isn't backed up by evidence in the story and/or the reporters' expertise.\nAnalysis: This is where a reporter adds context to the story based on reporting and other knowledge drawn from other expertise on the topic developed outside of directly reporting the story.\nColor: Details that add vivid and specific descripions and contribute to the story's narrative and help paint a picture specific to this time, place or situation. Beyond \"just the facts.\"\nOther: A sentence role we haven't seen before!\n</definitions>\n\nHere is the student article:\n\n<student article>\n[Lede] With the election of Cardinal Robert Prevost as Pope Leo XIV, the College of Cardinals sent a clear message of continuity with the reformist agenda of his predecessor, Pope Francis.\n[Nut Graf] But despite Leo’s reputation as having a quieter, more disciplined personality than that of Francis, the conservative ire that has roiled Catholicism during the previous pontificate is likely to continue with this first American pope.\n\n\n[Nut Graf] Traditionalist Catholics, especially in the United States — where much of the opposition to Francis was based — had yearned for a new pope who would rein in or even reverse changes that Francis made to foster a more inclusive church, where authority was shared and everyone could be heard.\n\n</student article>\n\nHere is the professionally edited article:\n\n<professional article>\n[Lede] USG Presidential Election season is upon us.\n[Transition] Tomorrow begins the next phase of the campaign!\n[Supporting Detail] Expect to see buttons, leaflets and signs.\n[Nut Graf] So we spoke with the five presidential candidates about their platforms and how each of them plans to connect with us, the voters.\n[Attribution] Nataly Lozano reports.\n[Background Information] \n\nIt’s election season for USC students once again, as the USG presidential candidates begin their physical campaigns on Tuesday.\n[Evidence] \n\nAccording to the USG Speaker of the Senate Alvaro Flores, voter turnout has been low for recent USG elections.\n[Counterargument] So how are this year’s candidates engaging with USC students and getting them to vote?\n[Lede] \n\nWe asked the five presidential candidates that same question.\n[Nut Graf] \n\nWe begin with third-year Sociology major Miko Mariscal and her DEI initiative, which aims to emphasize diversity, equity, and inclusion as a forefront of her platform.\n[Quote] \n\nMiko Mariscal: These conversations need to be had and they all intersect and flowed down to a lot of our campaign points, whether it be the club resource guide or career career development, as well as our transparency tracker.\n[Supporting Detail] And then finally, our very large one as Trojan family weekend and our funding goals.\n[Attribution] \n\nMariscal’s vice presidential candidate, third-year Communication major Andrew Taw, highlights the events the duo has planning to promote their platform this week.\n[Quote] \n\nAndrew Taw: This upcoming Wednesday, we’re going to be giving out pizza, We’re going to be on Trousdale.\n[Supporting Detail] We’re hoping that people come talk to us.\n[Supporting Detail] We’re going to have like a QR code that like links all our platform points.\n[Supporting Detail] And also we’ve just been meeting with like RSOs, our registered student organizations recently.\n[Source Opinion] So we’ve just been excited.\n[Attribution] \n\nFourth-year Political Science major and presidential candidate Aidan Feighery agrees with the notion that face-to-face communication reigns supreme.\n[Quote] \n\nAidan Feighery: I strongly prefer to have an actual conversation with people.\n[Quote] I don’t like to just talk at them and assume that they got the message.\n[Quote] I prefer to have a conversation with them and hear what they care about and they think is important.\n[Supporting Detail] \n\nFeighery’s platform focuses on sexual assault prevention at USC.\n[Quote] \n\nAidan Feighery: The most important part of our platform focuses on a real solution to sexual assault prevention at USC.\n[Evidence] We saw in fall of 2021 that we didn’t have enough protections then, and since then we have only had those protections rolled back due to disaffiliation.\n[Lede] \n\nIn the same vein, Divya Jakatdar, third year Political Science student and presidential candidate, believes in serving the USC student body in four main ways.\n[Quote] \n\nDivya Jakatdar: Our goal is really to improve upon four areas of student life, which are accessibility, affordability, community and transparency.\n[Supporting Detail] And then we basically bucketed our priority projects within this.\n[Analysis] \n\nJakatdar’s campaigning involves more personal ways to get voters engaged.\n[Quote] \n\nDivya Jakatdar: We’re making a lot of videos showing, you know, a little bit of lightheartedness, but also just to really engage voters, because I think students often get disengaged with student government.\n[Lede] \n\nNavya Singh, 3rd year Business Administration student and vice presidential candidate, also believes in hands-on engagement for voters.\n[Quote] \n\nNavya Singh: So this upcoming Friday from 11 to 12 we have like professional head shots because I am a Marshall student, but I feel like without Marshall, I wouldn’t have gotten the chance to really like learn the importance of like resumes, of head shots, of networking.\n[Source Opinion] So, I really want to try to implement those types of things.\n[Background Information] \n\nIn terms of her platform, Singh has used her time as a senator to emphasize her qualifications for the job.\n[Quote] \n\nNavya Singh: So, just try to talk to people on the day-to-day.\n[Quote] Whether that’s classes or just anywhere tabling-wise, just to see, like, why it is that people don’t vote, and like, what we can do about that because I think that talking to people — listening is a very important skill that I learned personally as a Senator and Devon is fantastic at.\n[Supporting Detail] \n\nAnother candidate who is a current USG senator, 2nd year Political Economy major Yoav Gillath, is using previous experience on his presidential platform.\n[Quote] \n\nYoav Gillath: So our three biggest priorities on our platform is community outreach, mental health and restructuring.\n[Quote] \n\nYoav Gillath: We also want to keep pushing for the Trojans give back Dining Dollar donation program that I founded that’s been able to donate $55,000 worth of food to unhoused individuals and food insecure students.\n[Background Information] \n\nGillath’s vice presidential candidate, Quantitative Biology major Monica Rodriguez, is passionate about getting new voters involved this election season.\n[Quote] \n\nMonica Rodriguez: For some of these people, it’s their first time, like voting in an election and they’re like juniors.\n[Source Opinion] And so like that really says a lot about like our campaign and like our intentions to make sure that we’re we’re actively seeking out people who haven’t been historically involved in making sure that, you know, they realize that they’re just as important to us.\n[Lede] \n\nAs you’ve heard, this year’s USG candidates look to engage more with the student body.\n[Nut Graf] Only time will tell if their efforts pay off in voter turnout.\n[Supporting Detail] \n\nVoting opens February 21st and closes the following Sunday, February 26th.\n[Other] \n\nFor Annenberg Media, I’m Nataly Lozano.\n\n</professional article>\n\nPlease give the student concise feedback on the ways their structure differs from the professional article \nand how they might change their article to match the professional article. \nIf you don't see tags on the student article (or tags that say [Analyzing...], please infer for yourself what function they play). \nPoint out missing structural components or changes they might make. If they already have some of the right structural components in the right places, mention that and compliment them.\nDon't write more than a paragraph total and directly reference the structural labels where possible (but don't format them differently, just return plain text, with all the appropriate capitalization patterns). \nSpeak directly to the student -- i.e. use words like \"You should\" or \"We recommend\" instead of \"The student article.\".",
    "comparison": "Your article has a strong Lede and a clear Nut Graf that outlines the significance of Cardinal Robert Prevost's election, which is commendable. However, you should include more background information to provide context about the previous papacy and the significance of this election, similar to how the professional article outlines the election season for USC students. Additionally, you should integrate more evidence and quotes from relevant sources to support your claims, as seen throughout the professional article. Consider adding counterarguments to address differing views within the Catholic community, and use transitions to guide readers effectively through your points. Including these elements will strengthen your article and create a more engaging narrative."
}
print(t['prompt'])
pyperclip.copy(t['prompt'])

I will show you a student-written draft and a professionally-edited article, each with structural annotations for each sentence. The structural annotations are the following:

<definitions>
Lede: The opening sentence or sentences of a story that grabs the reader's attention and highlights the most important and newsworthy aspects, usually including the "who, what, when, where, why and how" elements in succinct language.
Nut Graf: Context for the story: Why the audience cares, why the topic matters and other crucial details relevant to the story.
Background Information: Contextual information related to the main topic of the story.
Attribution: Person, organization or document that provides information.
Evidence: Information that supports the main point.
Quote: Exact words from someone you interviewed or documents you reviewed.
Counterargument: This is a crucial part of the story that displays evidence that the reporter has considered and consulted experts on possible rebuttals to the story's main topic or contention.
Transition: A sentence that indicates a new idea or topic is being introduced.
Supporting Detail: More information about an idea or topic that is intended to help the reader take action, deepen their understanding of the information or draw a conclusion.
Source Opinion: An opinionated statement from an individual who spoke directly or indirectly to a reporter.
Author Point of View: An opinion expressed by the author that isn't backed up by evidence in the story and/or the reporters' expertise.
Analysis: This is where a reporter adds context to the story based on reporting and other knowledge drawn from other expertise on the topic developed outside of directly reporting the story.
Color: Details that add vivid and specific descripions and contribute to the story's narrative and help paint a picture specific to this time, place or situation. Beyond "just the facts."
Other: A sentence role we haven't seen before!
</definitions>

Here is the student article:

<student article>
[Lede] With the election of Cardinal Robert Prevost as Pope Leo XIV, the College of Cardinals sent a clear message of continuity with the reformist agenda of his predecessor, Pope Francis.
[Nut Graf] But despite Leo’s reputation as having a quieter, more disciplined personality than that of Francis, the conservative ire that has roiled Catholicism during the previous pontificate is likely to continue with this first American pope.


[Nut Graf] Traditionalist Catholics, especially in the United States — where much of the opposition to Francis was based — had yearned for a new pope who would rein in or even reverse changes that Francis made to foster a more inclusive church, where authority was shared and everyone could be heard.

</student article>

Here is the professionally edited article:

<professional article>
[Lede] USG Presidential Election season is upon us.
[Transition] Tomorrow begins the next phase of the campaign!
[Supporting Detail] Expect to see buttons, leaflets and signs.
[Nut Graf] So we spoke with the five presidential candidates about their platforms and how each of them plans to connect with us, the voters.
[Attribution] Nataly Lozano reports.
[Background Information]

It’s election season for USC students once again, as the USG presidential candidates begin their physical campaigns on Tuesday.
[Evidence]

According to the USG Speaker of the Senate Alvaro Flores, voter turnout has been low for recent USG elections.
[Counterargument] So how are this year’s candidates engaging with USC students and getting them to vote?
[Lede]

We asked the five presidential candidates that same question.
[Nut Graf]

We begin with third-year Sociology major Miko Mariscal and her DEI initiative, which aims to emphasize diversity, equity, and inclusion as a forefront of her platform.
[Quote]

Miko Mariscal: These conversations need to be had and they all intersect and flowed down to a lot of our campaign points, whether it be the club resource guide or career career development, as well as our transparency tracker.
[Supporting Detail] And then finally, our very large one as Trojan family weekend and our funding goals.
[Attribution]

Mariscal’s vice presidential candidate, third-year Communication major Andrew Taw, highlights the events the duo has planning to promote their platform this week.
[Quote]

Andrew Taw: This upcoming Wednesday, we’re going to be giving out pizza, We’re going to be on Trousdale.
[Supporting Detail] We’re hoping that people come talk to us.
[Supporting Detail] We’re going to have like a QR code that like links all our platform points.
[Supporting Detail] And also we’ve just been meeting with like RSOs, our registered student organizations recently.
[Source Opinion] So we’ve just been excited.
[Attribution]

Fourth-year Political Science major and presidential candidate Aidan Feighery agrees with the notion that face-to-face communication reigns supreme.
[Quote]

Aidan Feighery: I strongly prefer to have an actual conversation with people.
[Quote] I don’t like to just talk at them and assume that they got the message.
[Quote] I prefer to have a conversation with them and hear what they care about and they think is important.
[Supporting Detail]

Feighery’s platform focuses on sexual assault prevention at USC.
[Quote]

Aidan Feighery: The most important part of our platform focuses on a real solution to sexual assault prevention at USC.
[Evidence] We saw in fall of 2021 that we didn’t have enough protections then, and since then we have only had those protections rolled back due to disaffiliation.
[Lede]

In the same vein, Divya Jakatdar, third year Political Science student and presidential candidate, believes in serving the USC student body in four main ways.
[Quote]

Divya Jakatdar: Our goal is really to improve upon four areas of student life, which are accessibility, affordability, community and transparency.
[Supporting Detail] And then we basically bucketed our priority projects within this.
[Analysis]

Jakatdar’s campaigning involves more personal ways to get voters engaged.
[Quote]

Divya Jakatdar: We’re making a lot of videos showing, you know, a little bit of lightheartedness, but also just to really engage voters, because I think students often get disengaged with student government.
[Lede]

Navya Singh, 3rd year Business Administration student and vice presidential candidate, also believes in hands-on engagement for voters.
[Quote]

Navya Singh: So this upcoming Friday from 11 to 12 we have like professional head shots because I am a Marshall student, but I feel like without Marshall, I wouldn’t have gotten the chance to really like learn the importance of like resumes, of head shots, of networking.
[Source Opinion] So, I really want to try to implement those types of things.
[Background Information]

In terms of her platform, Singh has used her time as a senator to emphasize her qualifications for the job.
[Quote]

Navya Singh: So, just try to talk to people on the day-to-day.
[Quote] Whether that’s classes or just anywhere tabling-wise, just to see, like, why it is that people don’t vote, and like, what we can do about that because I think that talking to people — listening is a very important skill that I learned personally as a Senator and Devon is fantastic at.
[Supporting Detail]

Another candidate who is a current USG senator, 2nd year Political Economy major Yoav Gillath, is using previous experience on his presidential platform.
[Quote]

Yoav Gillath: So our three biggest priorities on our platform is community outreach, mental health and restructuring.
[Quote]

Yoav Gillath: We also want to keep pushing for the Trojans give back Dining Dollar donation program that I founded that’s been able to donate $55,000 worth of food to unhoused individuals and food insecure students.
[Background Information]

Gillath’s vice presidential candidate, Quantitative Biology major Monica Rodriguez, is passionate about getting new voters involved this election season.
[Quote]

Monica Rodriguez: For some of these people, it’s their first time, like voting in an election and they’re like juniors.
[Source Opinion] And so like that really says a lot about like our campaign and like our intentions to make sure that we’re we’re actively seeking out people who haven’t been historically involved in making sure that, you know, they realize that they’re just as important to us.
[Lede]

As you’ve heard, this year’s USG candidates look to engage more with the student body.
[Nut Graf] Only time will tell if their efforts pay off in voter turnout.
[Supporting Detail]

Voting opens February 21st and closes the following Sunday, February 26th.
[Other]

For Annenberg Media, I’m Nataly Lozano.

</professional article>

Please give the student concise feedback on the ways their structure differs from the professional article
and how they might change their article to match the professional article.
If you don't see tags on the student article (or tags that say [Analyzing...], please infer for yourself what function they play).
Point out missing structural components or changes they might make. If they already have some of the right structural components in the right places, mention that and compliment them.
Don't write more than a paragraph total and directly reference the structural labels where possible (but don't format them differently, just return plain text, with all the appropriate capitalization patterns).
Speak directly to the student -- i.e. use words like "You should" or "We recommend" instead of "The student article.".